### ISSUE TITLE
Is Contribution Guide Planned? 

### ISSUE THREAD

**Issue by zeonchew** [mcknly/breadboard-os#2]
Hi @mcknly,

I find this project is very interesting. Just wonder, are you planning to create a contribution guidelines so that people's who wants to contribute to the project could get started in contributing to the project?

**Comment by zeonchew** [comment]
My bad. Found the Contribution notes in readme. Somehow missed it earlier 😂

**Comment by mcknly** [comment]
@zeonchew looking forward to your contributions! Thanks for interest in the project!
