### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by annonymous12343** [mcknly/breadboard-os#23]
/home/an0n1m0us/breadboard-os/services/usb_service.c:23:10: fatal error: tusb.h: No such file or directory
   23 | #include "tusb.h"
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/my-bbos-proj.dir/build.make:146: CMakeFiles/my-bbos-proj.dir/services/usb_service.c.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1882: CMakeFiles/my-bbos-proj.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by mcknly** [comment]
TinyUSB is a submodule of the Pico SDK, try: `git submodule update --init` in your pico-sdk directory

**Comment by annonymous12343** [comment]
I tryied it and now it worked. Thanks!
